### ISSUE TITLE
When both privileged and unprivileged stores are full they may not end up leaving `reserved_space_for_other_jobs_in_mb` free space on disk

### ISSUE THREAD

**Issue by jvshahid** [cloudfoundry/garden-runc-release#104]
## Description

The Diego team environment (electron-cannon) ran out of disk space.  Checking the store disk usage, it looks like both privileged and unprivileged stores are using less than the configured threshold.  That said, their combined usage doesn't leave `reserved_space_for_other_jobs_in_mb` space for the rest of the components.

## Environment

* garden-runc-release version: 
```
garden-runc              1.16.7*                 d2a6ecb+  
```
* IaaS: GCP
* Stemcell version: 
```
bosh-google-kvm-ubuntu-xenial-go_agent/97.18
```
* Kernel version: 
```
4.15.0-34-generic
```

## Logs

Below are the stores configuration files:
```yml
diego-cell/058fe0af-50ce-419f-8dd6-8a94b7ad44f3:/var/vcap/data/grootfs/store# cat /var/vcap/jobs/garden/config/privileged_grootfs_config.yml 
store: /var/vcap/data/grootfs/store/privileged
tardis_bin: /var/vcap/packages/grootfs/bin/tardis
newuidmap_bin: /var/vcap/packages/garden-idmapper/bin/newuidmap
newgidmap_bin: /var/vcap/packages/garden-idmapper/bin/newgidmap
metron_endpoint: 127.0.0.1:3457
log_level: info
log_file: ""
create:
  exclude_image_from_quota: false
  skip_layer_validation: true
  with_clean: true
  without_mount: false
  disk_limit_size_bytes: 0
  insecure_registries: []
  remote_layer_client_certificates_path: /var/vcap/jobs/garden/certs
clean:
  threshold_bytes: 59463917568
diego-cell/058fe0af-50ce-419f-8dd6-8a94b7ad44f3:/var/vcap/data/grootfs/store# cat /var/vcap/jobs/garden/config/grootfs_config.yml            
store: /var/vcap/data/grootfs/store/unprivileged
tardis_bin: /var/vcap/packages/grootfs/bin/tardis
newuidmap_bin: /var/vcap/packages/garden-idmapper/bin/newuidmap
newgidmap_bin: /var/vcap/packages/garden-idmapper/bin/newgidmap
metron_endpoint: 127.0.0.1:3457
log_level: info
log_file: ""
create:
  exclude_image_from_quota: false
  skip_layer_validation: true
  with_clean: true
  without_mount: false
  disk_limit_size_bytes: 0
  insecure_registries: []
  remote_layer_client_certificates_path: /var/vcap/jobs/garden/certs
clean:
  threshold_bytes: 59463917568
```

As well as the output of `df`:
```
diego-cell/058fe0af-50ce-419f-8dd6-8a94b7ad44f3:/var/vcap/data/grootfs/store# du -sch unprivileged/volumes/* | sort -h
0       unprivileged/volumes/11eee470eb959b7c44554dbab3a683543c10f9176422fb1e5e1747c5fe4e2c45
0       unprivileged/volumes/5f70bf18a086007016e948b04aed3b82103a36bea41755b6cddfaf10ace3c6ef
0       unprivileged/volumes/bbfa4d38b816bfbe43db5bcbbb3d9ad2b6ccbf15bbd68858a0e1cc812ded700f
0       unprivileged/volumes/f38522a4c61bacdb7f307d72136b93ca1a908ed12e89842866d07ae77b606e1b
24K     unprivileged/volumes/004d8421c1de151b1a2bbcd612a0faaad7fee259cf695b129769014df7176b0c
24K     unprivileged/volumes/188b796e17860616267e018672dc662aadad8ffca375b8b1b3f4e5ed20628faa
24K     unprivileged/volumes/424d90953afb816cb4300bfaaf292988575bc87fc63a09f24c2603e2df1dff18
24K     unprivileged/volumes/4309453847449f9a3d5da01965e471dde5232b78e6d5dcc2720d306f3820dc5f
24K     unprivileged/volumes/4616b87bae24b3c60fecf33e76ee8fc987e8ff67777413c6a6d93178dcdd4467
24K     unprivileged/volumes/5306854272f9d4f72bd5365e279a167ea9ff6acaa22275864f72afc8aabc5ca6
24K     unprivileged/volumes/55f68f430d77253ef6ce1b93c05e372d9f81234de5b368299d20168f00f5169a
24K     unprivileged/volumes/6b10987dd78b3bcb9161d553dfe1554abba51b9eccf81a2a1e2ac2869c61412b
24K     unprivileged/volumes/809168d1e9c56ba91d9c518ac2578c1eab82f218910ac2162ba7e3bc7d20611b
24K     unprivileged/volumes/9e307ed2f049c99372804a08d9d168b29c676daffd216847448b51e5bb9297fa
24K     unprivileged/volumes/b2e00ca1f4041b468539459c90a9d0f2dccbbedd6d707a918c22e9396eef0f78
24K     unprivileged/volumes/b7c6747cf17585af5377ddc4e6ea3efd932109fb2c53207c41470fdd9dc157e1
24K     unprivileged/volumes/cdb76757acf27a0822f879e27bd6265fecfebc47cd2ff497f06e30319cd4f71c
24K     unprivileged/volumes/cf7369483605648ae7c6f39f6007e6bcf8de38f6afdda7458c017e9e75dfdf8d
24K     unprivileged/volumes/f5933e48dfc4ed122638c0a02e79bed966d852327042b79e2af5e10b58dc4c96
24K     unprivileged/volumes/fbe8ccb0d41d37be79146ad559a5a8dfa86331950cfbe4aaf51570d79c9d579d
1.2M    unprivileged/volumes/6a749002dd6a65988a6696ca4d0c4cbe87145df74e3bf6feae4025ab28f420f2
1.2M    unprivileged/volumes/8a788232037eaf17794408ff3df6b922a1aedf9ef8de36afdae3ed0b0381907b
2.6M    unprivileged/volumes/7bb1a80f5a756548a4bee1f7cc57e5df10f51031787eb96732682bbd262f498c
5.4M    unprivileged/volumes/03c4afdce0c3a2e9ce934ffd9ec5830f2e1f804f27ec07e86269e80da28e0213
6.2M    unprivileged/volumes/8ff6cc0109748a17063469a5cc679bd70c1d1f2dc07bb665d070d8a56c618d1f
6.6M    unprivileged/volumes/0f6057e40bafd35204951529312d736b5845c7004b16f499e4525de56a1034fe
6.6M    unprivileged/volumes/25c8bf3ccc8d675884788bc3144440ed700041b3ea64e533e6c27890016a377d
6.6M    unprivileged/volumes/35f74ba71478d64710cdd03825a049855573a89fa0d63ede99f28b03e60d9c75
6.6M    unprivileged/volumes/361d7ccd725d2755095004a6dccba5deb46f1a1a5b30e48208e1b544fd6b4a55
6.6M    unprivileged/volumes/3670aad92ea384e9647498ade896c0bbd6d9e310186f11e0b633a662078b0d5d
6.6M    unprivileged/volumes/3c5298c4f381a583e4767f81a08f736d7462277471987fe83e4d126c92007db5
6.6M    unprivileged/volumes/4a087650660d3592f24875813c288d03c957e7f12490d2cfbda1f7f051d3d466
6.6M    unprivileged/volumes/6d9a849a51433e03f9beb76f0ecc0bf412e8f6aba08f4bca10dd6673e0fa13b9
6.6M    unprivileged/volumes/79717db064a8f6e474a34145489a38c4c91cbb55dbabcbf8d521b91f4c2663b7
6.6M    unprivileged/volumes/9678980260bf8f3e4df052de8f2ceee2d3047465e95a0c9219a0dfcb948ec6bb
6.6M    unprivileged/volumes/bd643cee630185665a888a020235a8c81d86885cfcf68e4f42362daa554c7679
6.6M    unprivileged/volumes/c75e2a903fadad9775094cb6c24e79b61be376dad972afbb4cdb3b67fbda8e6b
6.6M    unprivileged/volumes/d9f459ee8d8fa7024271e43f8548abd9670798edcd13684ce5aa7b765f8200fa
6.6M    unprivileged/volumes/e45e065bdbf15c08d17f90695582595f84d965d44d7d184830fc953a1b781aab
8.6M    unprivileged/volumes/5f42fe5e0634ad123519878d47431808e59d048ee96ee6575df63dd89ef70ebf
8.6M    unprivileged/volumes/999f6aa8dc8a80daf592e60b3333ae1b8cd01682ba0cd1f817582c419c1d5172
8.8M    unprivileged/volumes/e1fe7658e5520a72c30cc95c6b28dd06148fe39fa521494cbce7757509a89190
904M    unprivileged/volumes/07a0fa9a54c3c2e8f89f0b722c0dfdc3c89f371366cfc0660bec542dc9ef6162
904M    unprivileged/volumes/11d1d00814acfa7f0579ad1b1ddfb3e9fbab89c0b4c9a35cb9df11e1fcdbd4c4
904M    unprivileged/volumes/22cf67e81f4681c5d5f2341243f412aaf80e192aa55bd39c9b8ada25519f7372
904M    unprivileged/volumes/33f78de282178d55c372b876c65ccc4bbea80306e6b8106348a577adc88462d9
904M    unprivileged/volumes/404f35992901f0b869cb3272e60c8b09cafa1b076470eee75e999849fa8ad6a3
904M    unprivileged/volumes/406cc5be93f7f2863e8bb9eba3dfafe42f0d0f6ab8e7b4ac48e194cc93bd2a08
904M    unprivileged/volumes/4073fde29662fc693c0ef07cf193ec3e2ad3f9c06ed39b18ccdcfe1667064baf
904M    unprivileged/volumes/47c2a6e633bf8abc70316bcf1dc69a67f834da78e572b62175925a7994888881
904M    unprivileged/volumes/4eee53a4e7ff21dd2d29dc898361f9934b2d5a29f4e53d459b70913dc0231258
904M    unprivileged/volumes/582b2a91bab807619d4e4a4a11aa84da10a403c4c18f7625c48b847686dfca1c
904M    unprivileged/volumes/5d2c8824d793677a31629bc1992ef60df0eb02382bbfbf72eb62d47239a142ef
904M    unprivileged/volumes/5f155272267bdb426c7369be36400424f04f245338e6c2ec0e971bc2dd3a2ac9
904M    unprivileged/volumes/64603a49ee43d472986cf06f11e4d50b9d243adf99cbe5a44031d773fe1a44f7
904M    unprivileged/volumes/69c6033fb40c80ae401d1cb7b928202ef8d176c6a3afe462ceca27132e0dc5fc
904M    unprivileged/volumes/6d4d3f4aa164ebc42d51e3746cad5ea10b0f6201ff989c151b0f9374c4ec1bc4
904M    unprivileged/volumes/6f6d56f9b11e923cb1b84f7f97a0a1e81cc2bd339991a6ad5d62e9065dde2029
904M    unprivileged/volumes/7e6cb84fab5ee1259ce06acaa097c84eeeb2684bf8612ff9c6f119250d1be0e1
904M    unprivileged/volumes/8784f3810ef09e1e1ddcd3dca32be7aff2cafe478b303fe79314ca5ae325aa0c
904M    unprivileged/volumes/889c89b249ff118450182238bb9396d8350f843bd90ac1a7f953fc6619124f2f
904M    unprivileged/volumes/89fb4defd61c6863e70fc839825d1f8f7bde3b84d62b8503402adac122740221
904M    unprivileged/volumes/96b9c09a36bab27fa5d45d2f9d3960cbdaa250f121e67fca2e7c80ca327944fe
904M    unprivileged/volumes/9e9ce3453d4aa89594fd7a2813b7f59d575af114352a7136070ef48e6cb3b21f
904M    unprivileged/volumes/ab5c2790663a753657783eef3f72b000ead95edf475293e2b1120071be54093d
904M    unprivileged/volumes/ade264c901316da75e66b67bf19082535f83bbaefe41c3d561018b11731f9e50
904M    unprivileged/volumes/bf9399f5c8cb00044ca2de7c701ac1fd3266ab64b2afae9a7e4159d8ff616ba1
904M    unprivileged/volumes/cbfe2e489890bafaf251fd759b52e8f0aa2b9f3a3dade83692561d89391dce9c
904M    unprivileged/volumes/cc38f59bda4690d5fca070c9140dfb0010d32332496f6b18c52f750a2da82239
904M    unprivileged/volumes/e24cb7bd2a1d53a2f186517be7e0041699959d503143c9038994858433ba3248
904M    unprivileged/volumes/e26baab0aad106be8911746ea82f4f8414d8506426c51b24b9ea83df9b997768
904M    unprivileged/volumes/ebc7a008445bb9d2c3b2b0c2a5b78b2e9a5acfc1c1b7c6f18b1f7b28143754a6
904M    unprivileged/volumes/ec820ec2844fe5d884868de664a5b6a8e92076754d658eefdde568ef50fcb201
904M    unprivileged/volumes/f65df587b05c22f9ecc7715bd9c1729ec1236ca05c6baa763bba82992c0c8dbb
29G     total
diego-cell/058fe0af-50ce-419f-8dd6-8a94b7ad44f3:/var/vcap/data/grootfs/store# du -sch privileged/volumes/* | sort -h  
904M    privileged/volumes/07a0fa9a54c3c2e8f89f0b722c0dfdc3c89f371366cfc0660bec542dc9ef6162
904M    privileged/volumes/11d1d00814acfa7f0579ad1b1ddfb3e9fbab89c0b4c9a35cb9df11e1fcdbd4c4
904M    privileged/volumes/22cf67e81f4681c5d5f2341243f412aaf80e192aa55bd39c9b8ada25519f7372
904M    privileged/volumes/33f78de282178d55c372b876c65ccc4bbea80306e6b8106348a577adc88462d9
904M    privileged/volumes/404f35992901f0b869cb3272e60c8b09cafa1b076470eee75e999849fa8ad6a3
904M    privileged/volumes/406cc5be93f7f2863e8bb9eba3dfafe42f0d0f6ab8e7b4ac48e194cc93bd2a08
904M    privileged/volumes/4073fde29662fc693c0ef07cf193ec3e2ad3f9c06ed39b18ccdcfe1667064baf
904M    privileged/volumes/47c2a6e633bf8abc70316bcf1dc69a67f834da78e572b62175925a7994888881
904M    privileged/volumes/4eee53a4e7ff21dd2d29dc898361f9934b2d5a29f4e53d459b70913dc0231258
904M    privileged/volumes/582b2a91bab807619d4e4a4a11aa84da10a403c4c18f7625c48b847686dfca1c
904M    privileged/volumes/64603a49ee43d472986cf06f11e4d50b9d243adf99cbe5a44031d773fe1a44f7
904M    privileged/volumes/6d4d3f4aa164ebc42d51e3746cad5ea10b0f6201ff989c151b0f9374c4ec1bc4
904M    privileged/volumes/6f6d56f9b11e923cb1b84f7f97a0a1e81cc2bd339991a6ad5d62e9065dde2029
904M    privileged/volumes/7e6cb84fab5ee1259ce06acaa097c84eeeb2684bf8612ff9c6f119250d1be0e1
904M    privileged/volumes/8784f3810ef09e1e1ddcd3dca32be7aff2cafe478b303fe79314ca5ae325aa0c
904M    privileged/volumes/889c89b249ff118450182238bb9396d8350f843bd90ac1a7f953fc6619124f2f
904M    privileged/volumes/89fb4defd61c6863e70fc839825d1f8f7bde3b84d62b8503402adac122740221
904M    privileged/volumes/96b9c09a36bab27fa5d45d2f9d3960cbdaa250f121e67fca2e7c80ca327944fe
904M    privileged/volumes/9e9ce3453d4aa89594fd7a2813b7f59d575af114352a7136070ef48e6cb3b21f
904M    privileged/volumes/ab5c2790663a753657783eef3f72b000ead95edf475293e2b1120071be54093d
904M    privileged/volumes/ade264c901316da75e66b67bf19082535f83bbaefe41c3d561018b11731f9e50
904M    privileged/volumes/bf9399f5c8cb00044ca2de7c701ac1fd3266ab64b2afae9a7e4159d8ff616ba1
904M    privileged/volumes/cc38f59bda4690d5fca070c9140dfb0010d32332496f6b18c52f750a2da82239
904M    privileged/volumes/e26baab0aad106be8911746ea82f4f8414d8506426c51b24b9ea83df9b997768
904M    privileged/volumes/ebc7a008445bb9d2c3b2b0c2a5b78b2e9a5acfc1c1b7c6f18b1f7b28143754a6
904M    privileged/volumes/ec820ec2844fe5d884868de664a5b6a8e92076754d658eefdde568ef50fcb201
904M    privileged/volumes/f65df587b05c22f9ecc7715bd9c1729ec1236ca05c6baa763bba82992c0c8dbb
24G     total
diego-cell/058fe0af-50ce-419f-8dd6-8a94b7ad44f3:/var/vcap/data/grootfs/store# 
```

## Cause

The `thresholder` doesn't take into account the disk usage from the privileged and unprivileged store. Instead, it considers each separately.

## Resolution
The `thresholder` should setup the config for both privileged and unprivileged container, possibly dividing the available space between the two.
