### ISSUE TITLE
Hanging garden create call

### ISSUE THREAD

**Issue by mariash** [cloudfoundry/garden-runc-release#148]
## Description

A request to Garden to create container is hanging on one of our Diego cells for several hours. When we looked into the garden logs we see the latest log for that container handle is `guardian.create.volume-creator.image-plugin-create.grootfs.create.groot-creating.start
ing` as well as a grootfs process stuck in a D state.

## Environment

* garden-runc-release version: 1.19.5
* Enabled configuration: 
```
bpm:
 enabled: true
garden:
 additional_bpm_volumes:
 - "/var/vcap/data/rep/shared/garden"
 - "/var/vcap/data/netplugin-server/sockets"
 cleanup_process_dirs_on_wait: true
 debug_listen_address: 127.0.0.1:17019
 default_container_grace_time: 0
 deny_networks:
 - 0.0.0.0/0
 destroy_containers_on_start: true
 experimental_rootless_mode: true
 listen_address: "/var/vcap/data/garden/sockets/garden.sock"
 network_plugin: "/var/vcap/packages/netplugin-shim/bin/garden-plugin"
 network_plugin_extra_args:
 - "--socket"
 - "/var/vcap/data/netplugin-server/sockets/network-shim.sock"
grootfs:
 skip_mount: true
 tls:
   ca_cert: "((grootfs_remote_layer_tls.ca))"
   cert: "((grootfs_remote_layer_tls.certificate))"
   key: "((grootfs_remote_layer_tls.private_key))"
logging:
 format:
   timestamp: rfc3339
```
* IaaS: gcp
* Stemcell version: 456.12
* Kernel version: 4.15.0-55-generic

## Steps to reproduce
n/a

## Logs
```
{"timestamp":"2019-08-26T19:03:19.334998820Z","level":"info","source":"guardian","message":"guardian.create.start","data":{"handle":"check-fc47b970-9cc8-4b7b-7d00-54f20f360680","session":"14604"}}
{"timestamp":"2019-08-26T19:03:19.348124959Z","level":"info","source":"guardian","message":"guardian.create.volume-creator.image-plugin-create.grootfs.create.groot-creating.start
ing","data":{"handle":"check-fc47b970-9cc8-4b7b-7d00-54f20f360680","imageID":"check-fc47b970-9cc8-4b7b-7d00-54f20f360680","original_timestamp":"2019-08-26T19:03:19.347639808Z","session":"14604.2.1","spec":{"BaseImageURL":{"ForceQuery":false,"Fragment":"","Host":"","Opaque":"","Path":"/var/vcap/packages/cflinuxfs3/rootfs.tar","RawPath":"","RawQuery":"","Scheme":"","User":null},"CleanOnCreate":true,"CleanOnCreateThresholdBytes":59463917568,"DiskLimit":0,"ExcludeBaseImageFromQuota":false,"GIDMappings":[{"HostID":4294967294,"NamespaceID":0,"Size":1},{"HostID":65536,"NamespaceID":1,"Size":4294901758}],"ID":"check-fc47b970-9cc8-4b7b-7d00-54f20f360680","Mount":false,"UIDMappings":[{"HostID":4294967294,"NamespaceID":0,"Size":1},{"HostID":65536,"NamespaceID":1,"Size":4294901758}]}}}
```
dontpanic output: https://drive.google.com/file/d/1ZE01tdItOBhmDUKG2XZKE4NeJrIuLz4O/view?usp=sharing

## Cause
Hanging grootfs create process:

```
701540 ?        D<l    0:12  |       \_ /var/vcap/packages/grootfs/bin/grootfs --config /var/vcap/data/garden/config/grootfs_config.yml create /var/vcap/packages/cflinuxfs3/root
fs.tar check-fc47b970-9cc8-4b7b-7d00-54f20f360680 store_mountpoint=/var/vcap/data CONTAINERD_DATA_DIR=/var/vcap/data/containerd MAXIMUS=4294967294 BASE_PATH=/var/vcap/jobs/garden
/bin DEPOT_PATH=/var/vcap/data/garden/depot TMPDIR=/var/vcap/data/tmp/user/4294967294/tmp DATA_DIR=/var/vcap/data GARDEN_CERTS_DIR=/var/vcap/jobs/garden/certs GARDEN_ROOTLESS_CON
FIG_DIR=/var/vcap/data/garden/config RUN_DIR=/var/vcap/sys/run/garden PATH=/var/vcap/jobs/garden/bin:/var/vcap/packages/garden-idmapper/bin:/var/vcap/packages/iptables/sbin:/var/
vcap/packages/guardian/bin:/var/vcap/jobs/garden/bin:/usr/local/bin:/usr/local/sbin:/usr/bin:/usr/sbin:/bin:/sbin:.: PWD=/var/vcap/jobs/garden GARDEN_DATA_DIR=/var/vcap/data/gard
en LOG_DIR=/var/vcap/sys/log/garden LANG=en_US.UTF-8 PIDFILE=/var/vcap/sys/run/garden/garden.pid SHLVL=0 HOME=/var/vcap/data/garden GARDEN_CONFIG_PATH=/var/vcap/data/garden/confi
g/config.ini GARDEN_CONFIG_DIR=/var/vcap/jobs/garden/config GARDEN_ROOTLESS_CERTS_DIR=/var/vcap/data/garden/certs XDG_RUNTIME_DIR=/var/run/user/4294967294 RUNTIME_BIN_DIR=/var/vc
ap/data/garden/bin SOCKET2ME_FD=4
```

## Resolution

We tried to bosh restart VM, but drain was hanging, due to insufficient resources, since all app load is on the other VM. So probably we will scale up and then restart.
